default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password


development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "localknot" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "localknot" } %>_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *primary_production
    database: localknot_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: localknot_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: localknot_production_cable
    migrations_paths: db/cable_migrate