name: Rails Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/test"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true

    - name: Initialize database
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load
        bundle exec rake db:seed

    # このステップを追加
    - name: Run Brakeman
      run: bundle exec brakeman -o tmp/brakeman.html

    - name: Run tests
      run: bundle exec rspec